services:

  #RE Cluster - Node 1
  re1:
    image: redislabs/redis:latest
    container_name: re1
    restart: unless-stopped
    tty: true
    cap_add: 
      - sys_resource
    ports:
      - "12000:12000"
      - "8443:8443"
      - "9443:9443"
    networks:
      re_pulsar:
        ipv4_address: 192.168.20.2

# Pulsar standalone
  pulsar:
    image: apachepulsar/pulsar-all:latest
    container_name: pulsar
    hostname: pulsar
    restart: on-failure
    networks:
      re_pulsar:
        ipv4_address: 192.168.20.3
    volumes:
      - ./rjsonsink/target/rjsonsink-0.0.1.nar:/pulsar/connectors/rjsonsink-0.0.1.nar
    ports:
      - "6650:6650"
      - "8080:8080"
    command: bash -c "exec bin/pulsar standalone"

networks:
  re_pulsar:
    name: re_net
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.20.0/24